include:
  - project: 'externalci/ci-image'
    ref: master
    file: '.gitlab-ci-default.yaml'

variables:
  POLYSWARM_API_ARCHIVE: https://github.com/polyswarm/polyswarm-api/archive

###############################################################
# Build Stage
###############################################################

dev-pypi:
  extends: .dev-pypi

###############################################################
# Test Stage
###############################################################

test-run310:
  tags:
    - kube-new
  image: python:3.10
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install $POLYSWARM_API_ARCHIVE/$CI_COMMIT_BRANCH.zip || pip install $POLYSWARM_API_ARCHIVE/develop.zip
    - pip install .[tests]
    - pytest -s -v

test-run311:
  tags:
    - kube-new
  image: python:3.11
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install $POLYSWARM_API_ARCHIVE/$CI_COMMIT_BRANCH.zip || pip install $POLYSWARM_API_ARCHIVE/develop.zip
    - pip install .[tests]
    - pytest -s -v

test-run312:
  tags:
    - kube-new
  image: python:3.12
  stage: test
  before_script:
    - pip install --upgrade pip setuptools
  script:
    - pip install $POLYSWARM_API_ARCHIVE/$CI_COMMIT_BRANCH.zip || pip install $POLYSWARM_API_ARCHIVE/develop.zip
    - pip install .[tests]
    - pytest -s -v

###############################################################
# Release Stage
###############################################################

release-pypi:
  extends: .release-pypi-public
