image: $REPO_URL/stage

stages:
  - build
  - test
  - release

variables:
  POLYSWARM_API_ARCHIVE: https://github.com/polyswarm/polyswarm-api/archive
  DOCKER_HOST: tcp://localhost:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

default:
  before_script:
    - pip install -q --upgrade pip
    - pip install -q $END_TO_END_LIB@$CI_COMMIT_REF_NAME || pip install -q $END_TO_END_LIB
    - e2e init

###############################################################
# Build Stage (jobs inside a stage run in parallel)
###############################################################

dev-pypi:
  tags:
    - kube-new
  stage: build
  before_script:
    - pip3 install -q --upgrade pip setuptools twine wheel bump2version
  script:
    - SHORT_SHA=$(git rev-parse --short HEAD) bumpversion --no-commit --no-tag local
    - python setup.py -q bdist_wheel
    - twine upload --skip-existing --disable-progress-bar --non-interactive dist/*

###############################################################
# Test Stage
###############################################################

test-run27:
  tags:
    - kube-new
  image: python:2.7
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    # install the version from the related branch or the one in the develop branch
    - pip install $POLYSWARM_API_ARCHIVE/$CI_COMMIT_BRANCH.zip || pip install $POLYSWARM_API_ARCHIVE/develop.zip
    - pip install -r requirements.txt
    - pip install .
    - pytest -s -v

test-run35:
  tags:
    - kube-new
  image: python:3.5
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install $POLYSWARM_API_ARCHIVE/$CI_COMMIT_BRANCH.zip || pip install $POLYSWARM_API_ARCHIVE/develop.zip
    - pip install -r requirements.txt
    - pip install .
    - pytest -s -v

test-run36:
  tags:
    - kube-new
  image: python:3.6
  stage: test
  before_script:
    - pip install --upgrade pip
  script:
    - pip install $POLYSWARM_API_ARCHIVE/$CI_COMMIT_BRANCH.zip || pip install $POLYSWARM_API_ARCHIVE/develop.zip
    - pip install -r requirements.txt
    - pip install .
    - pytest -s -v

###############################################################
# Release Stage
###############################################################

release-pypi:
  tags:
    - kube-new
  stage: release
  script:
    # release to internal pypi but do not tag yet
    - e2e release --skip-tag --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git
    # release to public pypi and tag
    - e2e release
      -u $PUBLIC_TWINE_USERNAME
      -p $PUBLIC_TWINE_PASSWORD
      -r $PUBLIC_TWINE_REPOSITORY_URL
      --remote https://github.com/polyswarm/$CI_PROJECT_NAME.git
